name: road_helperr
description: "A new Flutter project."

publish_to: "none"

version: 1.0.6+6

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  pin_code_fields: ^8.0.1
  video_player: ^2.8.6
  google_fonts: ^6.2.1
  gradient_slide_to_act: ^0.0.2
  shared_preferences: ^2.2.2
  image_picker: ^0.8.9
  geolocator: ^10.1.1
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  googleapis_auth: ^1.4.1
  googleapis: ^11.4.0
  connectivity_plus: ^6.0.5
  permission_handler: ^11.3.1
  location: ^5.0.3
  flutter_polyline_points: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.4
  uuid: ^4.4.2
  intl: ^0.19.0
  flutter_gemini: ^3.0.0
  flutter_markdown: ^0.7.7
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  flutter_local_notifications: ^16.3.0
  package_info_plus: ^4.2.0
  path_provider: ^2.1.2
  in_app_update: ^4.2.2
  url_launcher: ^6.1.5
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.1.6
  firebase_auth: ^4.15.3
  http_parser: ^4.0.2
  path: ^1.9.0
  camera: ^0.10.6
  # SOS Emergency Feature Dependencies
  battery_plus: ^4.1.0
  device_info_plus: ^9.1.2
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_background_service_ios: ^5.0.0
  local_auth: ^2.1.8
  telephony:
    path: ./sos_packages/telephony

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/home_icon/
    - assets/service-account-key.json
    - assets/
    - assets/videos/1.mp4
    - assets/videos/2.mp4
    - assets/videos/3.mp4
    - assets/map_style.json

  fonts:
    # Tajawal - General UI Text
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700

    # Cairo - Titles and Headlines
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

    # Changa - Conversational UI
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Changa-SemiBold.ttf
          weight: 600

    # Almarai - Data and Forms
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
