// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkVFjw0DdIBBto6L_gICNtOh12Hte-adI',
    appId: '1:550973504959:android:1bac56bec771b3fb78350a',
    messagingSenderId: '550973504959',
    projectId: 'road-helper-fed8f',
    databaseURL:
        'https://road-helper-fed8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'road-helper-fed8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAcwDXU4JH33Ox2CDrzlAuBD15U9pQIks',
    appId: '1:550973504959:ios:a26a564e584213fd78350a',
    messagingSenderId: '550973504959',
    projectId: 'road-helper-fed8f',
    databaseURL:
        'https://road-helper-fed8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'road-helper-fed8f.firebasestorage.app',
    iosBundleId: 'com.example.roadHelperr',
  );
}
